root_path: '.'
cache_folder: 'data'
yadisk_token: '<your-access-token>'

s3:
  endpoint_url: "127.0.0.1:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "lod-photobank-prod"

hydra:
  job:
    chdir: False